#!/usr/bin/env node
/**
 * FONT PIPELINE — copies the locale font subsets into public/fonts/ and generates one
 * stylesheet per locale.
 *
 * WHY A SCRIPT RATHER THAN AN IMPORT
 * ----------------------------------
 * Font loading is the largest controllable performance cost in this design (four families
 * across two scripts) and the largest CLS risk. Bundler-managed imports would attach BOTH
 * locales' CSS to every page, because the import graph is static while the locale is a runtime
 * value. Emitting real assets gives:
 *
 *   - true locale splitting: an English page never downloads an Arabic subset
 *   - explicit <link rel="preload"> for the two faces the first paint needs
 *   - stable, cacheable URLs that do not change when unrelated code changes
 *   - a payload that can be measured with `ls -l`, which is how the 180KB/locale budget is
 *     actually enforced
 *
 * LICENSING
 * ---------
 * These are the DOCUMENTED OPEN-SOURCE FALLBACK TIER from docs/TYPOGRAPHY_SYSTEM.md section 6.
 * All five families are SIL OFL 1.1 and are redistributed with their licence file.
 *
 * 29LT Zarid — the Phase 2 recommendation — is COMMERCIALLY LICENSED AND IS NOT INCLUDED. No
 * Zarid file is downloaded, bundled or referenced anywhere in this repository. When a licence is
 * obtained, add its files here and swap --type-family-display / --type-family-body in
 * src/styles/tokens.css. No component changes.
 *
 *   node scripts/build-fonts.mjs
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const modules = join(root, "node_modules", "@fontsource");
const outDir = join(root, "public", "fonts");

/**
 * A FACE SHIPS ONLY WHEN SOMETHING USES IT.
 *
 * The system declares three weights (400/500/600) and nothing below 400, but declaring a weight
 * is not the same as using one. The first run of this script shipped 600 in both scripts and
 * measured Arabic at 207.2 KB against a 180 KB budget — over, on the locale most likely to be
 * read on a mid-range Android.
 *
 * Auditing actual usage found the 600 faces are referenced NOWHERE: display type is set at 400
 * throughout (docs/ART_DIRECTION.md — "no weights below 400" is a floor, not an instruction to
 * use the ceiling), and the only 500 in the system is the Latin label tier and the active
 * navigation item. Arabic labels are specified at 400 precisely BECAUSE Arabic at ×1.12 already
 * carries more visual mass (docs/BILINGUAL_TYPE_TEST.md section 5).
 *
 * So the 600 faces were dropped. That is a decision the type system already implied; the budget
 * check is what surfaced it. Recorded as D4-3.
 *
 * The record tier (mono) ships in BOTH locales because it carries numerals, units and Latin
 * identifiers only — including inside Arabic prose.
 */
const FACES = {
  en: [
    // display + body
    { pkg: "ibm-plex-serif", subset: "latin", weight: 400, family: "IBM Plex Serif", preload: true },
    // UI, and the label tier at 500
    { pkg: "ibm-plex-sans", subset: "latin", weight: 400, family: "IBM Plex Sans", preload: true },
    { pkg: "ibm-plex-sans", subset: "latin", weight: 500, family: "IBM Plex Sans" },
    // record: numerals, units, Latin identifiers
    { pkg: "ibm-plex-mono", subset: "latin", weight: 400, family: "IBM Plex Mono" },
  ],
  ar: [
    // display + body
    { pkg: "noto-naskh-arabic", subset: "arabic", weight: 400, family: "Noto Naskh Arabic", preload: true },
    // UI and labels at 400 — Arabic reaches equal volume by size, not weight
    { pkg: "ibm-plex-sans-arabic", subset: "arabic", weight: 400, family: "IBM Plex Sans Arabic", preload: true },
    // 500 is used by the active navigation item only
    { pkg: "ibm-plex-sans-arabic", subset: "arabic", weight: 500, family: "IBM Plex Sans Arabic" },
    // record: the same Latin mono face, for numerals inside Arabic prose
    { pkg: "ibm-plex-mono", subset: "latin", weight: 400, family: "IBM Plex Mono" },
  ],
};

mkdirSync(outDir, { recursive: true });

let totalBytes = { en: 0, ar: 0 };
const report = [];

for (const [locale, faces] of Object.entries(FACES)) {
  const blocks = [
    `/* GENERATED by scripts/build-fonts.mjs — do not edit by hand.`,
    ` * Locale: ${locale}. Fallback tier (SIL OFL 1.1). Zarid is NOT licensed and NOT included.`,
    ` */`,
    "",
  ];

  for (const face of faces) {
    const file = `${face.pkg}-${face.subset}-${face.weight}-normal.woff2`;
    const source = join(modules, face.pkg, "files", file);

    if (!existsSync(source)) {
      console.error(`fonts: missing ${source}`);
      process.exit(1);
    }

    const dest = join(outDir, file);
    copyFileSync(source, dest);
    const bytes = statSync(dest).size;
    totalBytes[locale] += bytes;
    report.push({ locale, file, kb: (bytes / 1024).toFixed(1), preload: Boolean(face.preload) });

    blocks.push(
      `@font-face {`,
      `  font-family: '${face.family}';`,
      `  font-style: normal;`,
      `  font-weight: ${face.weight};`,
      // swap, with metric-matched fallbacks declared in tokens.css. An unmatched swap can
      // consume the entire 0.05 CLS budget in one reflow.
      `  font-display: swap;`,
      `  src: url(/fonts/${file}) format('woff2');`,
      `}`,
      ""
    );
  }

  writeFileSync(join(outDir, `${locale}.css`), blocks.join("\n"), "utf8");
}

// Redistribute the licences alongside the fonts, as OFL 1.1 requires.
for (const pkg of ["ibm-plex-serif", "ibm-plex-sans", "ibm-plex-sans-arabic", "ibm-plex-mono", "noto-naskh-arabic"]) {
  const licence = join(modules, pkg, "LICENSE");
  if (existsSync(licence)) {
    copyFileSync(licence, join(outDir, `LICENSE-${pkg}.txt`));
  }
}

console.log("font pipeline");
console.log("=".repeat(62));
for (const row of report) {
  console.log(
    `  ${row.locale}  ${row.file.padEnd(46)} ${row.kb.padStart(6)} KB${row.preload ? "  [preload]" : ""}`
  );
}
console.log("");
for (const [locale, bytes] of Object.entries(totalBytes)) {
  const kb = bytes / 1024;
  const status = kb <= 180 ? "within budget" : "OVER BUDGET";
  console.log(`  ${locale} total: ${kb.toFixed(1)} KB / 180 KB  ${status}`);
  if (kb > 180) process.exitCode = 1;
}
